export enum ApiPaths {
    GetRecipes = '/chefstory/getRecipes',
    GetIngredients = '/chefstory/getIngredients',
    GetBrands = '/chefstory/getBrands',
    GetSuppliers = '/chefstory/getSuppliers',
    GetAllRecipes = '/chefstory/getAllRecipes',
    GetAllIngredients = '/chefstory/getAllIngredients',
    GetAllBrands = '/chefstory/getAllBrands',
    GetAllSuppliers = '/chefstory/getAllSuppliers',
    AddRecipes = '/chefstory/updateRecipes/add',
    AddIngredients = '/chefstory/updateIngredients/add',
    AddBrands = '/chefstory/updateBrands/add',
    AddSuppliers = '/chefstory/updateSuppliers/add',
    UpdateRecipes = '/chefstory/updateRecipes/update',
    UpdateIngredients = '/chefstory/updateIngredients/update',
    UpdateBrands = '/chefstory/updateBrands/update',
    UpdateSuppliers = '/chefstory/updateSuppliers/update',
    RemoveRecipes = '/chefstory/updateRecipes/remove',
    RemoveIngredients = '/chefstory/updateIngredients/remove',
    RemoveBrands = '/chefstory/updateBrands/remove',
    RemoveSuppliers = '/chefstory/updateSuppliers/remove',
    GetConfig = '/chefstory/getConfig',
    Upload= '/chefstory/upload'
}

